// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetProcesses():Promise<Array<main.ProcessInfo>>;

export function Greet(arg1:string):Promise<string>;

export function Inject(arg1:number):Promise<void>;
